# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformAi < Formula
  desc "terraform-ai is an assistant for Terraform that utilizes OpenAI GPT to generate and apply HCL files for Terraform."
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.2/terraform-ai_darwin_arm64.tar.gz"
      sha256 "1ad82c8acfb0e590d2770858f623b08a2d95ffea35e6196ed17abbf93c84da04"

      def install
        bin.install "terraform-ai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.2/terraform-ai_darwin_amd64.tar.gz"
      sha256 "0c4c6a550f16f48149dfacfe1b517f10da34f52f0645fac23442fe675d112105"

      def install
        bin.install "terraform-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.2/terraform-ai_linux_amd64.tar.gz"
      sha256 "e537bcf920d7655881bfb1f268670d232106c691ede072f4820c8241d85312b4"

      def install
        bin.install "terraform-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.2/terraform-ai_linux_arm64.tar.gz"
      sha256 "553a75decad6d4c6d7098d460e04bbff61ea5f5fab17976453770271dea8de5e"

      def install
        bin.install "terraform-ai"
      end
    end
  end

  def caveats
    <<~EOS
      This assistant requires an OpenAI key.
    EOS
  end
end
