# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformAi < Formula
  desc "terraform-ai is an assistant for Terraform that utilizes OpenAI GPT to generate and apply HCL files for Terraform."
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.1/terraform-ai_darwin_arm64.tar.gz"
      sha256 "3280f030389deeddc104d3e1000b7f7663e5ce9c26dbd689f8930a612a2faf01"

      def install
        bin.install "terraform-ai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.1/terraform-ai_darwin_amd64.tar.gz"
      sha256 "9cc74bb66e74a9f5ba94b32246f5692aca474e4c9c694de017c98f3f42e64995"

      def install
        bin.install "terraform-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.1/terraform-ai_linux_arm64.tar.gz"
      sha256 "a3e5cfed90d850a92f264faefa7ddeabcc3432fd1f0630af2d9e87306b8b7419"

      def install
        bin.install "terraform-ai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubs-ai/terraform-ai/releases/download/v0.0.1/terraform-ai_linux_amd64.tar.gz"
      sha256 "efb0fee6830fe4860cae5e8e735810623c6bf1182e351a8ee3c17744ba816660"

      def install
        bin.install "terraform-ai"
      end
    end
  end

  def caveats
    <<~EOS
      This assistant requires an OpenAI key.
    EOS
  end
end
